/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "operaciones.h"

bool_t
xdr_Terminos (XDR *xdrs, Terminos *objp)
{
	register int32_t *buf;

	 if (!xdr_double (xdrs, &objp->a))
		 return FALSE;
	 if (!xdr_double (xdrs, &objp->b))
		 return FALSE;
	 if (!xdr_double (xdrs, &objp->resultado))
		 return FALSE;
	return TRUE;
}
