/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "operaciones.h"


void
operaciones_prog_1(char *host)
{
	CLIENT *clnt;
	struct Terminos  *result_1;
	struct Terminos  suma_1_arg;
	struct Terminos  *result_2;
	struct Terminos  producto_1_arg;
	struct Terminos  *result_3;
	struct Terminos  cociente_1_arg;

#ifndef	DEBUG
	clnt = clnt_create (host, OPERACIONES_PROG, OPERACIONES_VERS, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

	result_1 = suma_1(&suma_1_arg, clnt);
	if (result_1 == (struct Terminos *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_2 = producto_1(&producto_1_arg, clnt);
	if (result_2 == (struct Terminos *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_3 = cociente_1(&cociente_1_arg, clnt);
	if (result_3 == (struct Terminos *) NULL) {
		clnt_perror (clnt, "call failed");
	}
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	char *host;

	if (argc < 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	host = argv[1];
	operaciones_prog_1 (host);
exit (0);
}
