/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "operaciones.h"

struct Terminos *
suma_1_svc(struct Terminos *argp, struct svc_req *rqstp)
{
	static struct Terminos  result;

	/*
	 * insert server code here
	 */

	return &result;
}

struct Terminos *
producto_1_svc(struct Terminos *argp, struct svc_req *rqstp)
{
	static struct Terminos  result;

	/*
	 * insert server code here
	 */

	return &result;
}

struct Terminos *
cociente_1_svc(struct Terminos *argp, struct svc_req *rqstp)
{
	static struct Terminos  result;

	/*
	 * insert server code here
	 */

	return &result;
}
