/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "op.h"


void
op_prog_1(char *host, int op, struct NUM numeros)
{
	CLIENT *clnt;
	struct NUM  *result_1;
	struct NUM  suma_1_arg = numeros;
	struct NUM  *result_2;
	struct NUM  producto_1_arg = numeros;
	struct NUM  *result_3;
	struct NUM  cociente_1_arg = numeros;
	int operacion = op;

#ifndef	DEBUG
	clnt = clnt_create (host, OP_PROG, OP_VERS, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

switch(operacion)
{
	case 1:
		result_1 = suma_1(&suma_1_arg, clnt);
		if (result_1 ==  NULL) {
			clnt_perror (clnt, "call failed");
		}
		printf("%lf\n", (*result_1).i);
	break;
	case 2:
		result_2 = producto_1(&producto_1_arg, clnt);
		if (result_2 ==  NULL) {
			clnt_perror (clnt, "call failed");
		}
		printf("%lf\n", (*result_2).i);
	break;
	case 3:
		result_3 = cociente_1(&cociente_1_arg, clnt);
		if (result_3 ==  NULL) {
			clnt_perror (clnt, "call failed");
		}
		printf("%lf\n", (*result_3).i);

}

#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	char *host;
	float result;

	if(argc != 5)
	{
		printf("Usage ./op_client <#operacion> <i> <j> <host>\n");
		exit(0);
	}
	host = argv[4];

	struct NUM numeros = {atoi(argv[2]), atoi(argv[3])};

	switch(atoi(argv[1]))
	{
		case 1:
			op_prog_1 (host, 1, numeros);
			break;
		case 2:
			op_prog_1 (host, 2, numeros);
			break;
		case 3:
				op_prog_1 (host, 3, numeros);
				break;
		default:
				printf("1: Suma 2: Producto 3: Cociente\n");
				exit(1);
		}


exit (0);
}
