/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _RAND_H_RPCGEN
#define _RAND_H_RPCGEN

#define RPCGEN_VERSION	199506

#include <rpc/rpc.h>


#define RAND_PROG ((rpc_uint)0x31111111)
#define RAND_VERS ((rpc_uint)1)

#ifdef __cplusplus
#define INICIALIZA_RANDOM ((rpc_uint)1)
extern "C" void * inicializa_random_1(long *, CLIENT *);
extern "C" void * inicializa_random_1_svc(long *, struct svc_req *);
#define OBTIENE_SIGUIENTE_RANDOM ((rpc_uint)2)
extern "C" double * obtiene_siguiente_random_1(void *, CLIENT *);
extern "C" double * obtiene_siguiente_random_1_svc(void *, struct svc_req *);

#elif __STDC__
#define INICIALIZA_RANDOM ((rpc_uint)1)
extern  void * inicializa_random_1(long *, CLIENT *);
extern  void * inicializa_random_1_svc(long *, struct svc_req *);
#define OBTIENE_SIGUIENTE_RANDOM ((rpc_uint)2)
extern  double * obtiene_siguiente_random_1(void *, CLIENT *);
extern  double * obtiene_siguiente_random_1_svc(void *, struct svc_req *);

#else /* Old Style C */
#define INICIALIZA_RANDOM ((rpc_uint)1)
extern  void * inicializa_random_1();
extern  void * inicializa_random_1_svc();
#define OBTIENE_SIGUIENTE_RANDOM ((rpc_uint)2)
extern  double * obtiene_siguiente_random_1();
extern  double * obtiene_siguiente_random_1_svc();
#endif /* Old Style C */

#endif /* !_RAND_H_RPCGEN */
